DROP DATABASE IF EXISTS wowo;

-- 创建库
CREATE DATABASE wowo DEFAULT CHARACTER SET UTF8 COLLATE utf8_bin;

-- 切换库
USE wowo;

-- 管理员信息表
CREATE TABLE IF NOT EXISTS admininfo(
	aid INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT '管理员编号',
	aname VARCHAR(100) NOT NULL UNIQUE COMMENT '管理员姓名',
	pwd VARCHAR(100) NOT NULL COMMENT '密码',
	tel VARCHAR(15) UNIQUE COMMENT '联系方式',
	photo VARCHAR(100) COMMENT '图像',
	status INT(2)
)ENGINE = InnoDB AUTO_INCREMENT = 101 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO admininfo VALUES(0, 'navy', md5('123321'), '15096098010', NULL, 1),(0, 'yc', md5('123321'), '15096098011', NULL, 1);

-- 会员信息
CREATE TABLE IF NOT EXISTS memberinfo(
	mid INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '会员编号',
	nickName VARCHAR(100) NOT NULL UNIQUE COMMENT '昵称',
	realName VARCHAR(100) COMMENT '真实姓名',
	pwd VARCHAR(100) NOT NULL COMMENT '密码',
	tel VARCHAR(15) UNIQUE COMMENT '联系方式',
	email VARCHAR(100) NOT NULL UNIQUE COMMENT '注册邮箱',
	photo VARCHAR(100) COMMENT '图像',
	regDate DATETIME COMMENT '注册日期',
	status INT(2) COMMENT '状态'
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin; 

-- 类型表
CREATE TABLE IF NOT EXISTS typeinfo(
	tid INT(5) PRIMARY KEY AUTO_INCREMENT COMMENT '商品类型编号',
	tname VARCHAR(100) NOT NULL UNIQUE COMMENT '类型名称',
	intro VARCHAR(200) COMMENT '类型描述',
	status INT(2) COMMENT '类型状态'
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin; 

-- 店铺信息表
CREATE TABLE IF NOT EXISTS shopinfo(
	sid INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '店铺编号',
	sname VARCHAR(200) NOT NULL COMMENT '店铺名称',
	tid INT COMMENT '店铺类型',
	province VARCHAR(100) NOT NULL COMMENT '省份',
	city VARCHAR(100) NOT NULL COMMENT '城市',
	area VARCHAR(100) NOT NULL COMMENT '地区',
	addr VARCHAR(200) COMMENT '详细地址',
	intro VARCHAR(500) COMMENT '店铺简介',
	pics VARCHAR(200) COMMENT '店铺图片',
	tel VARCHAR(20) COMMENT '联系方式',
	license VARCHAR(200) COMMENT '营业执照',
	regDate DATETIME COMMENT '注册日期',
	startHours TIME COMMENT '开始营业时间',
	endHours TIME COMMENT '打烊时间',
	status INT(2) COMMENT '状态',
	CONSTRAINT FK_shopinfo_tid FOREIGN KEY(tid) REFERENCES typeinfo(tid)
)ENGINE = InnoDB AUTO_INCREMENT = 101 DEFAULT CHARSET=utf8 COLLATE=utf8_bin; 

-- 商品信息
CREATE TABLE IF NOT EXISTS goodsinfo(
	gid INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '商品编号',
	sid INT(11) COMMENT '所属店铺',
	gname VARCHAR(100) NOT NULL COMMENT '商品名称',
	pics VARCHAR(200) NOT NULL COMMENT '活动图片',
	intro VARCHAR(200) COMMENT '简介',
	price DECIMAL(10, 2) NOT NULL COMMENT '原价',
	rebate DECIMAL(2, 1) NOT NULL COMMENT '折扣',
	sdate DATE NOT NULL COMMENT '活动开始时间',
	edate DATE NOT NULL COMMENT '活动结束时间',
	detail TEXT COMMENT '活动详细',
	status INT(2) COMMENT '活动状态',
	CONSTRAINT FK_goodsinfo_sid FOREIGN KEY(sid) REFERENCES shopinfo(sid)
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin; 

-- 订单表
CREATE TABLE IF NOT EXISTS orderinfo(
	oid INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '订单编号',
	mid INT(11) COMMENT '会员编号',
	gid INT(11) COMMENT '商品编号',
	nums INT(11) COMMENT '购买数量',
	odate DATETIME COMMENT '下单日期',
	udate DATETIME COMMENT '使用日期',
	status INT(2) COMMENT '状态',
	CONSTRAINT FK_orderinfo_mid FOREIGN KEY(mid) REFERENCES memberinfo(mid),
	CONSTRAINT FK_orderinfo_gid FOREIGN KEY(gid) REFERENCES goodsinfo(gid)
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin; 

CREATE TABLE IF NOT EXISTS cartinfo(
	cid INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '订单编号',
	mid INT(11) COMMENT '会员编号',
	gid INT(11) COMMENT '商品编号',
	nums INT(11) COMMENT '购买数量',
	CONSTRAINT FK_cartinfo_mid FOREIGN KEY(mid) REFERENCES memberinfo(mid),
	CONSTRAINT FK_cartinfo_gid FOREIGN KEY(gid) REFERENCES goodsinfo(gid)
)ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin; 
